---
# The win_feature module only works on Windows Server editions
# and OpenSSH is in fact unavailable on Client installations.
- name: Install OpenSSH server and client
  when: enable_ssh and ansible_facts.os_installation_type == "Server"
  ansible.windows.win_shell: |
    Add-WindowsCapability -Name {{ capability }} -Online
  loop:
  - OpenSSH.Client~~~~0.0.1.0
  - OpenSSH.Server~~~~0.0.1.0
  loop_control:
    loop_var: capability
  become: true

- name: Ensure firewall rule for OpenSSH service exists
  when: enable_ssh and ansible_facts.os_installation_type == "Server"
  community.windows.win_firewall_rule:
    name: OpenSSH Server (sshd)
    localport: 22
    action: allow
    direction: in
    protocol: tcp
    state: present
    enabled: true
  become: true

- name: Set the default OpenSSH shell to PowerShell
  when: enable_ssh and ansible_facts.os_installation_type == "Server"
  ansible.windows.win_regedit:
    path: HKLM:\SOFTWARE\OpenSSH
    name: DefaultShell
    data: C:\Windows\System32\WindowsPowerShell\v1.0\powershell.exe
    type: string
    state: present

- name: Ensure .ssh configuration directory exists for user vagrant
  when: enable_ssh and ansible_facts.os_installation_type == "Server"
  ansible.windows.win_file:
    path: C:\Users\vagrant\.ssh
    state: directory

- name: Add insecure vagrant ssh key to authorized_keys
  when: enable_ssh and add_vagrant_ssh_pubkey and ansible_facts.os_installation_type == "Server"
  community.windows.win_lineinfile:
    line: "{{ lookup('url', 'https://raw.github.com/hashicorp/vagrant/master/keys/vagrant.pub', split_lines=False) }}"
    path: C:\Users\vagrant\.ssh\authorized_keys
    create: true

- name: Start and enable OpenSSH service
  when: enable_ssh and ansible_facts.os_installation_type == "Server"
  ansible.windows.win_service:
    name: sshd
    state: started
    start_mode: auto
  become: true
