---
- name: Rearrange drives
  when: rearrange_drives
  ansible.builtin.include_tasks: Windows/rearrange_drives.yaml

- name: Install Windows updates
  when: update_windows
  ansible.builtin.include_tasks: Windows/update_windows.yaml

- name: Update precompiled .NET assemblies
  when: precompile_dotnet
  community.windows.win_dotnet_ngen:

- name: Set PowerShell execution policy
  when: execution_policy
  ansible.builtin.include_tasks: Windows/set_powershell_executionpolicy.yaml

- name: Ensure password for vagrant never expires
  when: disable_vagrant_password_expiry
  ansible.windows.win_user:
    name: vagrant
    password_never_expires: true
  become: true

- name: Suppress prompt for network location
  when: disable_network_location_prompt
  ansible.windows.win_regedit:
    path: HKLM:\SYSTEM\CurrentControlSet\Control\Network\NewNetworkWindowOff
    state: present
  become: true

- name: Set all network connections to Private
  when: set_all_networks_private
  ansible.windows.win_shell: >
    Get-NetConnectionProfile | Set-NetConnectionProfile -NetworkCategory "Private"
  become: true

- name: Enable RDP access
  when: enable_rdp
  ansible.builtin.include_tasks: Windows/enable_rdp.yaml

- name: Enable SSH access (Windows Server only)
  when: enable_ssh and ansible_facts.os_installation_type == "Server"
  ansible.builtin.include_tasks: Windows/enable_ssh.yaml

- name: Enable User Account Control
  when: enable_uac
  ansible.windows.win_regedit:
    path: HKLM:\SOFTWARE\Microsoft\Windows\CurrentVersion\Policies\System
    name: EnableLUA
    type: dword
    data: 1
  become: true

- name: Set power management plan
  when: power_plan
  community.windows.win_power_plan:
    name: "{{ power_plan }}"
