---
- name: Install all updates and reboot as many times as needed
  ansible.windows.win_updates:
    category_names: '*'
    reboot: true
    reject_list: "VMware, Inc. - Net*"
  ignore_unreachable: true

- name: Wait for system to become reachable
  ansible.builtin.wait_for_connection:
