---
name: Ansible Lint
on: # yamllint disable-line rule:truthy
  - pull_request
  - push

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Check for GitHub token to determine reporter type
        run: |
          if [ -z "${{ secrets.REVIEWDOG_TOKEN }}" ]; then
              echo "REVIEWDOG_REPORTER=local" >> $GITHUB_ENV
          else
              echo "REVIEWDOG_REPORTER=github-pr-review" >> $GITHUB_ENV
          fi

      - name: Run ansible-lint
        uses: reviewdog/action-ansiblelint@v1
        with:
          fail_on_error: true
          filter_mode: nofilter
          level: info
          reporter: ${{ env.REVIEWDOG_REPORTER }}
          github_token: ${{ secrets.REVIEWDOG_TOKEN }}

      - name: Run yamllint
        uses: reviewdog/action-yamllint@v1
        with:
          fail_on_error: true
          filter_mode: nofilter
          level: info
          reporter: ${{ env.REVIEWDOG_REPORTER }}
          github_token: ${{ secrets.REVIEWDOG_TOKEN }}

      - name: Run markdownlint
        uses: reviewdog/action-markdownlint@v0
        with:
          fail_on_error: true
          filter_mode: nofilter
          level: info
          reporter: ${{ env.REVIEWDOG_REPORTER }}
          github_token: ${{ secrets.REVIEWDOG_TOKEN }}
